### ISSUE TITLE
🤔关于部署服务安全性的疑惑与建议[欢迎大家一起讨论]

### ISSUE THREAD

**Issue by laorange** [ConnectAI-E/Dingtalk-OpenAI#169]
假如 **部署该服务的服务器的域名和IP** 被 **同样熟悉该项目的人**（以下以 *XX* 代称） 知晓，是否可以"借用"我搭建的服务？

如果仅是文本聊天，部署服务的服务器 是 钉钉的服务器 与 ChatGPT服务器的中转站，不会直接和用户接触，也就不会暴露域名和IP。

但我对"图片是否会让用户得知域名和IP"不太了解。我把疑问和建议以流程图的形式呈现：

- [x] 建议限制消息来源的**组织**id
    > 组织不会太多，倒是可以让开发者在测试过程中快速获取到？或者用管理员账号发消息"新增组织"的方式来授权？
    > 验证名称的话是否会出现伪造昵称的漏洞，类似于[这个评论](https://github.com/eryajf/chatgpt-dingtalk/commit/5d648a8ce46c517a8c4243e5a8bbff081a30bc7b#r107297574)中所提到的问题？🤔
- [ ] 建议改以uuid命名图片和[聊天记录的md文件](https://github.com/eryajf/chatgpt-dingtalk/blob/8c04c74640545dcf9bb29fd922b1b734236c293a/pkg/process/process_request.go#L301)

```mermaid
graph TD
      B{用户能否<br/>通过图片地址<br/>得知域名/IP?};
      B -->|是| C[安全性存疑];
			C --> D[以时间命名的文件<br/>容易被试出]
			C --> D1[他人借用我的服务]
			D1 --> E1[建议限制消息来源的组织]
			E1 --> END
			D --> E[建议改以uuid命名<br/>图片和聊天记录文件]
			E --> END
      B -->|否| F1{是否可以<br/>将域名告知用户?<br/>如:chat.eryajf.net};
			F1 --> |是| C
			F1 --> |否| END
```

---

限制组织ID是考虑以下场景：

1. 我因为要使用机器人的私聊功能，（应该是）无法使用 `allow_groups` 来限制使用者；
2. 群友比较多，也很难使用 `allow_users` 来指定个别使用者；
3. *XX* 知道了我部署服务的IP和域名，他创建了他自己的钉钉组织，在他创建组织的后台添加了机器人，并按将**我服务器的IP和域名**填入下图，然后组织名、群名、甚至用户名都改成与我一致的：
![img](https://camo.githubusercontent.com/d1fb30021c99616b75b8daebb6b6e0452ddc72245fb720d6660abd55d8bd1b8b/68747470733a2f2f63646e2e737461746963616c792e636f6d2f67682f657279616a662f74752f6d61696e2f696d672f696d6167655f32303232313230395f3136333635322e706e67)

**Comment by eryajf** [comment]
有心了，首先肯定一个问题，安全隐患是存在的。
我觉得首先可以考虑增加一个组织ID，用于缩小限制的范围。但是这有一个问题，就是回调的消息当中，其实没有这个字段，因此没有办法做比对校验，虽然[这个文档](https://open.dingtalk.com/document/robots/enterprise-created-chatbot)里介绍了有这个字段，但实际测试返回内容里没有。

那么，可能需要进一步，通过填写机器人的app-key，app-secret来获取到企业的一些信息，如此一来，会增加配置的难度，不晓得会不会有人觉得这样比较麻烦。看了下免费的钉钉，后台接口调用次数10000次/月，而使用这种方式会消耗这个额度，不太了解现实中企业对这个是否在意。

此问题需再探讨。

另外使用UUID命名文件这个没有问题，可以加。

**Comment by eryajf** [comment]
看起来，最开始留的一个TODO，现在必须要做了，需要对回调信息进行解密，然后判断是否为当前企业的正常回调消息。

**Comment by zjjEcho** [comment]
话说是不是计算一下签名就可以了，签名里面包含机器人的appSecret
<img width="886" alt="image" src="https://user-images.githubusercontent.com/5327847/229707293-7f50cc86-094e-4115-aeb4-32329e36860c.png">

**Comment by eryajf** [comment]
> 话说是不是计算一下签名就可以了，签名里面包含机器人的appSecret <img alt="image" width="886" src="https://user-images.githubusercontent.com/5327847/229707293-7f50cc86-094e-4115-aeb4-32329e36860c.png">

https://github.com/eryajf/chatgpt-dingtalk/pull/171

**Comment by eryajf** [comment]
下午将校验admin的字段也做了调整，改成userid了

https://github.com/eryajf/chatgpt-dingtalk/pull/175

**Comment by laorange** [comment]
已用两个组织进行了测试，通过 `app_secrets` 进行限制确实有效！🎉项目因此更加完善了，非常感谢！

```
INFO [🚀 The HTTP Server is running on :8090]
WARN [该请求不合法，可能是其他企业或者未经允许的应用调用所致，请知悉！]
```

**Comment by eryajf** [comment]
@laorange readme更新了个钉钉群，快来进群交流
