### ISSUE TITLE
帮助菜单展示问题

### ISSUE THREAD

**Issue by Timoshao** [ConnectAI-E/Dingtalk-OpenAI#218]
HELP参数设置如下： 
 -e HELP="=================================\n\n  🙋 单聊 👉 单独聊天\n\n  📣 串聊 👉 带上下文聊天\n\n  🔃 重置 👉 重置带上下文聊天\n\n  🚀 帮助 👉 显示帮助信息\n\n  🌈 模板 👉 内置的prompt\n\n  🎨 图片 👉 根据prompt生成图片\n\n  =================================\n\n  🚜 例：@我发送 空 或 帮助 将返回此帮助信息\n\n💪 Power By https://github.com/eryajf/chatgpt-dingtalk" \
 为什么展示样式没有换行
 
![image](https://user-images.githubusercontent.com/108260847/233951756-a0672968-4e86-4751-aaed-ca2c4966ec39.png)

**Comment by eryajf** [comment]
> HELP参数设置如下： -e HELP="=================================\n\n 🙋 单聊 👉 单独聊天\n\n 📣 串聊 👉 带上下文聊天\n\n 🔃 重置 👉 重置带上下文聊天\n\n 🚀 帮助 👉 显示帮助信息\n\n 🌈 模板 👉 内置的prompt\n\n 🎨 图片 👉 根据prompt生成图片\n\n =================================\n\n 🚜 例：@我发送 空 或 帮助 将返回此帮助信息\n\n💪 Power By [eryajf/chatgpt-dingtalk](https://github.com/eryajf/chatgpt-dingtalk)" 为什么展示样式没有换行
> 
> ![image](https://user-images.githubusercontent.com/108260847/233951756-a0672968-4e86-4751-aaed-ca2c4966ec39.png)

看下镜像是不是最新的

**Comment by Timoshao** [comment]
> 

是最新的，刚刚删除容器 删除镜像重新部署一遍还是这样的

**Comment by eryajf** [comment]
我这边实际测试是正常的，你再执行这个命令看看镜像的创建时间是什么时候的？

```sh
$ docker inspect eryajf/chatgpt-dingtalk | grep Created
        "Created": "2023-04-22T00:17:16.954628668Z",
```

**Comment by Timoshao** [comment]
> 我这边实际测试是正常的，你再执行这个命令看看镜像的创建时间是什么时候的？
> 
> ```shell
> $ docker inspect eryajf/chatgpt-dingtalk | grep Created
>         "Created": "2023-04-22T00:17:16.954628668Z",
> ```
执行结果如下：
![image](https://user-images.githubusercontent.com/108260847/234463441-917b0401-f5d6-4b5a-82cc-ba8e4caed0e4.png)
