### ISSUE TITLE
配置服务器对接微软的azure openai，始终报500的错误

### ISSUE THREAD

**Issue by dongbeixiaohuo** [ConnectAI-E/Dingtalk-OpenAI#229]
配置服务器对接微软的azure openai，始终报500的错误，服务器端可以看到钉钉机器人信息发送到了服务器，但是报错“gpt request error: error, status code 500”
具体配置只调整了以下几项，其余未做调整保持默认。
azure_on: true # 如果是true，则会走azure的openai接口
azure_api_version: "2023-03-15-preview"
azure_resource_name: "资源名"
azure_deployment_name: "部署的模型名"
azure_openai_token: "apikey"

**Comment by eryajf** [comment]
> 需要在 `BASE_URL` 中配置你的 Azure OpenAI 地址，如：`https://xxxx.openai.azure.com/`

这个配置项可以留空，默认会指向官方的地址。

@dongbeixiaohuo 如果方便的话，晚上我跟你一块儿测试一下你这个情况

**Comment by mattliu007** [comment]
同样问题，不过我用openai原生url也是500，不知道到底是哪边问题

**Comment by dongbeixiaohuo** [comment]
> > 需要在 `BASE_URL` 中配置你的 Azure OpenAI 地址，如：`https://xxxx.openai.azure.com/`
> 
> 这个配置项可以留空，默认会指向官方的地址。
> 
> @dongbeixiaohuo 如果方便的话，晚上我跟你一块儿测试一下你这个情况

今天回来太晚，才看到，感谢，明天啥时候方便一起测试？
我后来排查，官方给的curl地址格式“https://xx.openai.azure.com/openai/deployments/gpt35/chat/completions?api-version=2023-03-15-preview \
我发现config文件中的注释是https://forkway-test.openai.azure.com/openai/deployments/test-dev/chat/completions\?api-version\=2023-03-15-preview \ 遇上对比version后多了一个”\“，是否格式有影响？

**Comment by mattliu007** [comment]
> > > 需要在 `BASE_URL` 中配置你的 Azure OpenAI 地址，如：`https://xxxx.openai.azure.com/`
> > 
> > 
> > 这个配置项可以留空，默认会指向官方的地址。
> > @dongbeixiaohuo 如果方便的话，晚上我跟你一块儿测试一下你这个情况
> 
> 今天回来太晚，才看到，感谢，明天啥时候方便一起测试？ 我后来排查，官方给的curl地址格式“https://xx.openai.azure.com/openai/deployments/gpt35/chat/completions?api-version=2023-03-15-preview 我发现config文件中的注释是[https://forkway-test.openai.azure.com/openai/deployments/test-dev/chat/completions\?api-version\=2023-03-15-preview](https://forkway-test.openai.azure.com/openai/deployments/test-dev/chat/completions%5C?api-version%5C=2023-03-15-preview) \ 遇上对比version后多了一个”\“，是否格式有影响？

刚看到回复，尝试了多种组合配置还是不行，可协助测试

**Comment by eryajf** [comment]
@dongbeixiaohuo  已更新了配置文件的说明信息，请根据说明信息正确配置，然后重启服务进行验证。

通过 @mattliu007 同学提供的配置信息，我这边验证已经是可以走通的了。

**Comment by dongbeixiaohuo** [comment]
![Dingtalk_20230527114106](https://github.com/ConnectAI-E/Dingtalk-OpenAI/assets/73542526/1f7b0c47-0f2e-4145-a0c7-a12e3f807007)
如图截图，仍然报500的错误，反复改了很多次。或者哪里能查到日志，是key错了还是地址错了等？

**Comment by dongbeixiaohuo** [comment]
> > > > 需要在 `BASE_URL` 中配置你的 Azure OpenAI 地址，如：`https://xxxx.openai.azure.com/`
> > > 
> > > 
> > > 这个配置项可以留空，默认会指向官方的地址。
> > > @dongbeixiaohuo 如果方便的话，晚上我跟你一块儿测试一下你这个情况
> > 
> > 
> > 今天回来太晚，才看到，感谢，明天啥时候方便一起测试？ 我后来排查，官方给的curl地址格式“https://xx.openai.azure.com/openai/deployments/gpt35/chat/completions?api-version=2023-03-15-preview 我发现config文件中的注释是[https://forkway-test.openai.azure.com/openai/deployments/test-dev/chat/completions?api-version=2023-03-15-preview](https://forkway-test.openai.azure.com/openai/deployments/test-dev/chat/completions%5C?api-version%5C=2023-03-15-preview) \ 遇上对比version后多了一个”\“，是否格式有影响？
> 
> 刚看到回复，尝试了多种组合配置还是不行，可协助测试
方便把你跑通的配置发一下吗？我反复改了好多次配置，仍然500报错

**Comment by eryajf** [comment]
> ![Dingtalk_20230527114106](https://user-images.githubusercontent.com/73542526/241353854-1f7b0c47-0f2e-4145-a0c7-a12e3f807007.jpg) 如图截图，仍然报500的错误，反复改了很多次。或者哪里能查到日志，是key错了还是地址错了等？

看起来似乎是你deployment_name 写的不对，你再看看azure那里给你的完整url是什么
