### ISSUE TITLE
🙋 最新release1.0.21没有window的二进制包了嘛？

### ISSUE THREAD

**Issue by Martinzz** [ConnectAI-E/Dingtalk-OpenAI#233]
## 问题反馈

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/chatgpt-dingtalk/issues)，请勿重复提交issue。

**重要：提交问题时，请务必带上输出日志，以及个人排查的成果。**

**Comment by eryajf** [comment]
下个版本就会有了

**Comment by eryajf** [comment]
最新版本已经有了
