### ISSUE TITLE
运行docker镜像后，运行docker logs chatgpt，有如下报错

### ISSUE THREAD

**Issue by MysTer1ous** [ConnectAI-E/Dingtalk-OpenAI#240]
## 问题反馈

![image](https://github.com/ConnectAI-E/Dingtalk-OpenAI/assets/28255159/117b0b0b-1ceb-4d87-9a32-a21609706190)

**Comment by eryajf** [comment]
你的部署方式是什么，这里是指应用的秘钥。配置方式参照readme说明应该不会有问题的。

**Comment by MysTer1ous** [comment]
docker run -itd --name chatgpt -p 8090:8090  -v `pwd`/config.yml:/app/config.yml --restart=always  dockerproxy.com/eryajf/chatgpt-dingtalk:latest
用的docker

**Comment by MysTer1ous** [comment]
用的docker部署的第一种方式

**Comment by eryajf** [comment]
其中config.yml中的 credentials 需要正确配置。

**Comment by MysTer1ous** [comment]
不好意思，看漏了一行，非常感谢大佬，运行后
![image](https://github.com/ConnectAI-E/Dingtalk-OpenAI/assets/28255159/2cfc6a08-ac13-4c7c-8f3d-552000a2510d)

**Comment by MysTer1ous** [comment]
> 不好意思，看漏了一行，非常感谢大佬，运行后 ![image](https://user-images.githubusercontent.com/28255159/243373104-2cfc6a08-ac13-4c7c-8f3d-552000a2510d.png)

请求openai的api失败，我的机器有外网了，curl试过ok的

**Comment by eryajf** [comment]
如果机器能直接连，那就把 http_proxy 留空

**Comment by MysTer1ous** [comment]
好的，我的机器已经开了代理，我又设置了http_proxy=127.0.0.1:xxxx，谢谢大佬，点star
