### ISSUE TITLE
使用stream模式时图片不显示

### ISSUE THREAD

**Issue by TakakuraAnzu** [ConnectAI-E/Dingtalk-OpenAI#241]
![L1VzZXJzL2lsbHlhL0xpYnJhcnkvQXBwbGljYXRpb24gU3VwcG9ydC9EaW5nVGFsa01hYy8xOTAyOTExODM5X3YyL0ltYWdlRmlsZXMvMTY4NjE5NTg3MjU5N181MkQ1MkZGMy0xRTQ3LTQ1NkItODk5QS1CQzE5QkM0QjM2OEMucG5n](https://github.com/ConnectAI-E/Dingtalk-OpenAI/assets/19336824/9e68da41-9f7c-4afc-869f-8a4f972bb17a)
![L1VzZXJzL2lsbHlhL0xpYnJhcnkvQXBwbGljYXRpb24gU3VwcG9ydC9EaW5nVGFsa01hYy8xOTAyOTExODM5X3YyL0ltYWdlRmlsZXMvMTY4NjE5NTk0NTI3NV9GOTlEMDdBNi1DOTdGLTQ4MDMtOTE2OC1ERDdFN0YzQjZEOEMucG5n](https://github.com/ConnectAI-E/Dingtalk-OpenAI/assets/19336824/6e46abb0-bad1-4b3b-87c9-a57ce450a3ba)
使用stream模式创建机器人，对话输出的图片不显示，后台查看对应的生成地址是http://nas.123asd789.top:8090/images/20230608-113102.png
我对server_url使用nginx进行代理，用浏览器访问这个网址是正常的

**Comment by TakakuraAnzu** [comment]
这个域名是纯ipv6访问，ipv4不能访问

**Comment by eryajf** [comment]
目前最新版本的代码会把图片上传到钉钉服务器，使用服务地址拼接的图片地址只是一个兜底。

所以理论图片功能是没有影响的。
