### ISSUE TITLE
请求限制的问题

### ISSUE THREAD

**Issue by aaronyyan** [ConnectAI-E/Dingtalk-OpenAI#244]
话说，，这个有接口请求次数限制吗，使用jemter，30s内发出10个请求后返回内容提示错误了，如下图：

![image](https://github.com/ConnectAI-E/Dingtalk-OpenAI/assets/39476555/2f2b7a5a-41c2-4936-86fb-427f51eaa2f3)

**Comment by eryajf** [comment]
免费的key很早就有这个限制了，你可以到openai官网看一下。

**Comment by aaronyyan** [comment]
看到了，谢谢
