### ISSUE TITLE
能否配置成当串聊超过最大文本限制时，自动删除上下文前面的部分，使之避免超过限制强制重置对话

### ISSUE THREAD

**Issue by suyunkai** [ConnectAI-E/Dingtalk-OpenAI#246]
目前的逻辑是当串聊超过了最大文本限制时，忘记所有对话，全部重置。能否调整为当达到设置的字符数量时，自动删除掉上下文中最早的超出部分，使上下文总量一直在限制之内，这样的逻辑就会像和网页版一样，可以一直串聊对话了，当超出最大token后，会自动忘记最早的内容。
我尝试自己修改代码实现这个功能失败了，希望作者能够考虑一下加入这个功能。

**Comment by gltjk** [comment]
我记得见过其他的类似app会在串聊信息累计过多后把之前最早的部分信息压缩（即通过AI总结，再把总结的结果当上下文一起发），这可能可以是一个思路。
