### ISSUE TITLE
🙋 使用Azure OpenAI接口返回404，并提示The API deployment for this resource does not exist，但是可以直接通过curl或者postman访问。

### ISSUE THREAD

**Issue by saynone** [ConnectAI-E/Dingtalk-OpenAI#274]
#### 日志报错如下：

<img width="1184" alt="image" src="https://github.com/ConnectAI-E/Dingtalk-OpenAI/assets/10138402/7e9ff33a-a3a0-429d-b826-4ae1594f9922">

####  配置文件config.yml如下：

<img width="635" alt="image" src="https://github.com/ConnectAI-E/Dingtalk-OpenAI/assets/10138402/90b2bd08-7d41-4920-87ca-7df8b3a0ee90">

#### 直接使用curl访问如下：

<img width="1196" alt="image" src="https://github.com/ConnectAI-E/Dingtalk-OpenAI/assets/10138402/a560939f-14b8-4110-a398-63019a5cbacc">

**Comment by sofia-lrf** [comment]
同问+1

**Comment by eryajf** [comment]
应该是当前版本更新之后，改坏了Azure的某些地方，可以先用老的版本，我看看是怎么回事儿。

两位方便的话，可通过邮箱联系我，我这边目前没有Azure的资源，所以需要借用一下你们的资源。
