### ISSUE TITLE
请教：是否能将模型换位本地部署的ChatGLM2-6B

### ISSUE THREAD

**Issue by stuarthe** [ConnectAI-E/Dingtalk-OpenAI#279]
## 问题反馈

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/chatgpt-dingtalk/issues)，请勿重复提交issue。

**重要：提交问题时，请务必带上输出日志，以及个人排查的成果。**

如题。如果可以，应该在哪里修改？

**Comment by wangr0031** [comment]
配置文件中加入下面的配置：
```
model：“chatglm”
```
同时配置的base_url里面要有`/v1/completions`的访问路径

**Comment by stuarthe** [comment]
收到。谢谢！
才发现ChatGLM2 自己做了一个 openai_api.py ，直接就可以调用。
