### ISSUE TITLE
是否支持 gpt stream 参数设为 true 时钉钉消息的不断更新

### ISSUE THREAD

**Issue by Yaocool** [ConnectAI-E/Dingtalk-OpenAI#285]
当 GPT 参数设为 True 时，GPT 产生的响应为 SSE 协议的数据，在钉钉侧发送消息时是否支持将每一条 GPT 推理产生的结果动态更新到钉钉上？（即通俗的说就是在钉钉侧机器人发送消息的内容能否一个字/一个词的进行更新）
PS: 这个 stream 并非钉钉服务端的 Stream 模式，而是 GPT 的 stream 参数

**Comment by eryajf** [comment]
目前钉钉侧没有给出这种形式的接口，因此暂时无法支持
