### ISSUE TITLE
unmarshal request body failed: unexpected end of JSON input？

### ISSUE THREAD

**Issue by acdiost** [ConnectAI-E/Dingtalk-OpenAI#3]
https://open.dingtalk.com/document/robots/enterprise-created-chatbot
```json
{
    "conversationId": "xxx",
    "atUsers": [
        {
            "dingtalkId": "xxx",
            "staffId":"xxx"
        }
    ],
    "chatbotCorpId": "dinge8a565xxxx",
    "chatbotUserId": "$:LWCP_v1:$Cxxxxx",
    "msgId": "msg0xxxxx",
    "senderNick": "杨xx",
    "isAdmin": true,
    "senderStaffId": "user123",
    "sessionWebhookExpiredTime": 1613635652738,
    "createAt": 1613630252678,
    "senderCorpId": "dinge8a565xxxx",
    "conversationType": "2",
    "senderId": "$:LWCP_v1:$Ff09GIxxxxx",
    "conversationTitle": "机器人测试-TEST",
    "isInAtList": true,
    "sessionWebhook": "https://oapi.dingtalk.com/robot/sendBySession?session=xxxxx",
    "text": {
        "content": " 你好"
    },
    "msgtype": "text"
}
```

**Comment by eryajf** [comment]
这些是钉钉回调过来的信息，目前只用到了 senderNick ，sessionWebhook 以及 content，其他的暂时没有用到。

我没有理解你说的配置缺少一些是指的哪些？

**Comment by acdiost** [comment]
我现在遇到的问题是在钉钉 `@` 了机器人后，服务器端日志无任何响应，找不到问题出在哪里，钉钉相关配置已经完成了；服务器上测试直接访问 localhost:8090 ,chatgpt 有返回。

**Comment by acdiost** [comment]
![image](https://user-images.githubusercontent.com/38416288/207002193-6009d81e-c34a-4483-a77c-6a805a9da2e2.png)
![image](https://user-images.githubusercontent.com/38416288/207002724-fe4d49c9-8787-41e5-b545-0243e66444c8.png)
![image](https://user-images.githubusercontent.com/38416288/207002909-f5d7b627-368e-461a-8ca4-6d84ac58c5b0.png)

**Comment by eryajf** [comment]
你是通过什么方式部署的呢，应该是你的config.json配置信息有误的原因，看 #1  这里的说明

**Comment by acdiost** [comment]
docker 部署的
![image](https://user-images.githubusercontent.com/38416288/207009904-ff0d3643-8b29-4b28-bc78-0e9bf49f15d5.png)
![image](https://user-images.githubusercontent.com/38416288/207010012-e07c678c-b4b7-43e7-8d10-81eb0c53cba0.png)

**Comment by mrhaoji** [comment]
docker 部署和命令行直接部署都遇到 

`unmarshal request body failed: unexpected end of JSON input`

然后钉钉那边报和 #1 一样的错误提示

`消息接收地址校验失败（请确保公网可访问该地址，如无有效SSL证书，可选择禁用证书校验）`

不过应该和钉钉没关系，是程序端错误导致钉钉那边校验通不过

**Comment by acdiost** [comment]
我这里也是 `unmarshal request body failed: unexpected end of JSON input`，我还以为是缺少钉钉相关的配置。

**Comment by eryajf** [comment]
看起来应该是程序有问题，我现在看一下

**Comment by acdiost** [comment]
直接请求接口会报 `unmarshal request body failed: unexpected end of JSON input` 的错误。
未正确加载 Nginx 的配置导致无法正常使用。
